#! /usr/bin/env bash

# shellcheck disable=SC2034,SC1090

# host scripts
scripts=(
    'dconf'
    'ssh'
    'vim'
    'headless'
    'smb-share-docs'
)

# ssh
ssh_keys=(
    'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINZLqJ1Xw8iKuq8iNkd+sDi8PzSELP/UIS6RnpQ1cYls me@xps-9305'
)

# smb-share-docs
smb_user='docs'
smb_password=''
smb_share_name='docs'
smb_absolute_path="/var/home/${smb_user}/docs"