#! /usr/bin/env bash

# shellcheck disable=SC2034,SC1090

# host scripts
scripts=(
    'vim'
    'bash'
    'flatpak'
    'dconf'
    'hide-firefox'
    'signal'
    'vscodium'
)
                                   
# flatpak
flatpaks=(
    'com.github.tchx84.Flatseal'
    'com.mattjakeman.ExtensionManager'
    'org.gnome.Firmware'
    'org.gnome.World.PikaBackup'
    'io.gitlab.librewolf-community'
    'org.freedesktop.Platform.ffmpeg-full/x86_64/24.08'
    'com.spotify.Client'
    'com.valvesoftware.Steam'
    'com.yubico.yubioath'
    'org.chromium.Chromium'
    'org.gimp.GIMP'
    'com.bitwarden.desktop'
    'org.gnome.Boxes'
    'io.ente.photos'
    'org.signal.Signal'
)

